name: Pre release

on:
  [push]

permissions: 
   contents: write


jobs:
  build:
    name: Auto Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: "3.11"
      - name: Install Dependencies
        run: pip install pyyaml install-jdk tqdm psutil requests pyinstaller pyarmor rtoml-0.10.0-cp311-none-win_amd64.whl
      - name: Generate Bundle
        run: |
          python generate-bundle.py
      - name: Auto release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          files: |
            dist/*.exe
