permissions:
  contents: write

on:
  [push]

jobs:
  build:
    name: Auto Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: "3.11"
      - name: Install Dependencies and Generate Bundle
        run: |
          python generate-bundle.py
      - name: Auto release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ matrix.os }}
          prerelease: true
          files: |
            dist/*

      - name: Upload File
        uses: "ryand56/r2-upload-action@master"
        with:
          r2-account-id: "${{ secrets.R2_ACCOUNT_ID }}"
          r2-access-key-id: "${{ secrets.R2_ACCESS_KEY_ID }}"
          r2-secret-access-key: "${{ secrets.R2_SECRET_ACCESS_KEY }}"
          r2-bucket: "${{ secrets.R2_BUCKET }}"
          source-dir: dist
          destination-dir: ${{ matrix.os }}
          keep-file-fresh: 'true'