name: Pre release

on:
  [push]

permissions: 
   contents: write


jobs:
  build:
    name: Auto Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.6"
      - name: Generate Bundle
        run: |
          python generate-bundle.py
      - name: Install pyminifier
        run: pip install pyminifier
      - name: Minify Bundle
        run: sudo pyminifier -d /output --lzma *.py --nonlatin --obfuscate -replacement-length=1
      - name: Remove File
        run: |
          rm  -rf /output/generate-bundle.py
          rm  -rf /output/utils.py
      - name: Auto release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          files: |
            /output/*.py
